[project]
name = "kinoko7danmaku"
version = "3.7.2"
requires-python = ">=3.12"
dependencies = [
  "aiohttp>=3.12.14",
  "bilibili-api-python>=17.3.0",
  "edge-tts>=7.2.8",
  "faker>=37.12.0",
  "httpx[socks]>=0.28.1",
  "loguru>=0.7.3",
  "miniaudio>=1.71",
  "mutagen>=1.47.0",
  "pyaudio>=0.2.14",
  "pydantic>=2.11.7",
  "pydantic-settings>=2.11.0",
  "pyside6>=6.10.0",
  "pyside6-fluent-widgets[full]>=1.9.1",
  "qasync>=0.28.0",
  "qrcode>=8.2",
  "requests>=2.34.2",
  "sounddevice>=0.5.2",
  "stream-gears>=0.2.4",
  "tenacity>=9.1.2",
]

[dependency-groups]
dev = [
  "pre-commit>=4.3.0",
  "pyinstaller>=6.16.0",
  "pytest>=8.4.2",
  "pytest-asyncio>=1.2.0",
]

[tool.ruff]
line-length = 120
preview = true
fix = true
unsafe-fixes = true
show-fixes = true
required-version = ">=0.15.0"

[tool.ruff.lint]
select = [
  "FAST",
  "ANN001",
  "ANN201",
  "ANN202",
  "ANN204",
  "ANN205",
  "ANN206",
  "ARG",
  "ASYNC110",
  "ASYNC116",
  "ASYNC210",
  "ASYNC212",
  "ASYNC230",
  "ASYNC240",
  "ASYNC250",
  "ASYNC251",
  "S310",
  "FBT003",
  "B002",
  "B005",
  "B006",
  "B007",
  "B008",
  "B009",
  "B010",
  "B013",
  "B014",
  "B019",
  "B020",
  "B021",
  "B024",
  "B025",
  "B026",
  "B027",
  "B039",
  "B904",
  "COM",
  "C402",
  "C403",
  "C404",
  "C408",
  "C410",
  "C411",
  "C414",
  "C416",
  "C417",
  "C418",
  "C419",
  "C420",
  "DTZ",
  "ERA",
  "EXE",
  "I001",
  "ISC001",
  "ISC002",
  "ISC003",
  "PIE",
  "PYI009",
  "PYI010",
  "PYI011",
  "PYI012",
  "PYI013",
  "PYI016",
  "PYI017",
  "PYI019",
  "PYI020",
  "PYI021",
  "PYI024",
  "PYI026",
  "PYI030",
  "PYI033",
  "PYI034",
  "PYI036",
  "PYI041",
  "PYI042",
  "PYI055",
  "PYI061",
  "PYI062",
  "PYI063",
  "Q001",
  "Q002",
  "RSE102",
  "RET501",
  "RET505",
  "RET506",
  "RET507",
  "RET508",
  "SIM101",
  "SIM102",
  "SIM103",
  "SIM107",
  "SIM108",
  "SIM109",
  "SIM110",
  "SIM114",
  "SIM115",
  "SIM201",
  "SIM202",
  "SIM210",
  "SIM211",
  "SIM212",
  "SIM300",
  "SIM401",
  "SIM910",
  "TCH",
  "TID252",
  "TC",
  "FLY",
  "I",
  "C901",
  "N",
  "PERF",
  "E",
  "W",
  "D404",
  "D417",
  "D419",
  "F",
  "PGH",
  "PLC1901",
  "UP",
  "FURB",
  "RUF",
  "TRY",
]
ignore = [
  "COM812",
  "N802",
  "N803",
  "N814",
  "N815",
  "PGH003",
  "RUF001",
  "RUF002",
  "RUF003",
  "RUF006",
  "RUF012",
  "RUF067",
  "TRY003",
  "TRY301",
  "TRY400",
]

[tool.ruff.lint.mccabe]
max-complexity = 15

[tool.ruff.lint.flake8-pytest-style]
parametrize-names-type = "list"
parametrize-values-row-type = "list"
parametrize-values-type = "list"

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"

[tool.ruff.lint.flake8-type-checking]
runtime-evaluated-base-classes = [
  "pydantic.BaseModel",
  "sqlalchemy.orm.DeclarativeBase"
]

[tool.ruff.lint.flake8-unused-arguments]
ignore-variadic-names = true

[tool.ruff.lint.isort]
case-sensitive = true
lines-between-types = 1
order-by-type = true

[tool.ruff.lint.pylint]
allow-dunder-method-names = ["__tablename__", "__table_args__"]

[tool.ruff.format]
docstring-code-format = true
preview = true
quote-style = "single"
